document.writeln("<script type=\"text/javascript\" src=\"/js/mobile.js\"></script>");
document.writeln("<div class=\"nav_top\" style=\"width:100%;height:50px;\">");
document.writeln("<div class=\"top_gg\">");
document.writeln("<span class=\"domain\"><div id=\"logo\">{$siteurl}</div></span><div class=\"nav_bar_r1\">|&nbsp;&nbsp;請使用Ctrl+D進行收藏本站!&nbsp;&nbsp;|&nbsp;&nbsp;获取地址邮箱：521av@mail.com&nbsp;&nbsp;|&nbsp;&nbsp;");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("");

document.writeln("<div class=\"wrap mt20 nav\">");
document.writeln("");
document.writeln("	<div class=\"wrap\">");
document.writeln("<ul class=\"nav_menu clearfix\" >");
document.writeln("<li class=\"active\"><a href=\"/\">网站首页</a></li>");
document.writeln("<li><a href=\"/Html/94/\">中文字幕</a></li><li><a href=\"/Html/62/\">欧美激情</a></li><li><a href=\"/Html/109/\">三级电影</a></li><li><a href=\"/Html/101/\">卡通动漫</a></li><li><a href=\"/Html/63/\">精选套图</a></li><li><a href=\"/Html/84/\">情色小说</a></li><li><a target=\"_blank\" style=\" color: gold; \" href=\"https://www.62pe.com/main.html?m=reg\">太阳城赌场</a></li>");
document.writeln("</ul>");
document.writeln("</div></div>");
document.writeln("");

document.writeln("<div class=\"wrap nav\">");
document.writeln("");
document.writeln("	<div class=\"wrap\">");
document.writeln("<ul class=\"nav_menu clearfix\" >");
document.writeln("<li class=\"active\"><a href=\"/Html/60/\">国产精品</a></li>");
document.writeln("<li><a href=\"/Html/89/\">自拍偷拍</a></li><li><a href=\"/Html/93/\">清纯大学生</a></li><li><a href=\"/Html/91/\">网红主播</a></li><li><a href=\"/Html/87/\">美腿丝袜</a></li><li><a href=\"/Html/90/\">人妻少妇</a></li><li><a href=\"/Html/88/\">综合视频</a></li><li><a style=\" color: gold; \" target=\"_blank\" href=\"https://www.jsf7.com/main.html?m=reg\">AV女优发牌</a></li>");
document.writeln("</ul>	");
document.writeln("</div></div>");
document.writeln("");
document.writeln("");
document.writeln("<div class=\"wrap nav\">");
document.writeln("");
document.writeln("	<div class=\"wrap\">");
document.writeln("<ul class=\"nav_menu clearfix\" >");
document.writeln("<li class=\"active\"><a href=\"/Html/110/\">无码AV</a></li>");
document.writeln("<li><a href=\"/Html/100/\">精品女优</a></li><li><a href=\"/Html/111/\">素人娇妻</a></li><li><a href=\"/Html/112/\">美颜巨乳</a></li><li><a href=\"/Html/113/\">强奸乱伦</a></li><li><a href=\"/Html/114/\">JAVHD</a></li><li><a href=\"/help.html\">帮助教程</a></li><li><a style=\" color: gold; \" target=\"_blank\"  href=\"https://www.13hvip.com/main.html?m=reg\">皇冠体育</a></li>");
document.writeln("</ul>	");
document.writeln("</div></div>");
document.writeln("</div>");
document.writeln("<div class=\"mt20\"></div>");
document.writeln("</div>");
document.writeln("");
